server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: encoding-service

management:
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: encoding-service
  prometheus:
    metrics:
      export:
        enabled: true
