spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.master.yaml

  datasource:
    url: jdbc:postgresql://${PROCESSING_DB_HOST}:${PROCESSING_DB_PORT}/${PROCESSING_DB_NAME}
    username: ${PROCESSING_DB_USER}
    password: ${PROCESSING_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

minio:
  url: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

grpc:
  client:
    storage-service:
      address: static://storage-service:${STORAGE_GRPC_SERVICE_PORT}
      negotiationType: plaintext

  server:
    port: ${PROCESSING_GRPC_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
