spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8070/realms/voyagrr
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      properties:
        spring.json.add.type.headers: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring.json.use.type.headers: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.master.yaml
  datasource:
    url: jdbc:postgresql://processing-service-database:5432/processing_service_database
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: voyagrr-media

grpc:
  client:
    storage-service:
      address: static://storage-service:9091
      negotiationType: plaintext
  server:
    port: 9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
