services:
  keycloak-database:
    image: postgres:17
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    ports:
      - '5433:5432'
    volumes:
      - keycloak-database-data:/var/lib/postgresql/data
    networks:
      - voyagrr-net

  user-service-database:
    image: postgres:17
    environment:
      POSTGRES_DB: user_service_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432'
    volumes:
      - user-database-data:/var/lib/postgresql/data
    networks:
      - voyagrr-net

  storage-service-database:
    image: postgres:17
    environment:
      POSTGRES_DB: storage_service_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5432'
    volumes:
      - storage-database-data:/var/lib/postgresql/data
    networks:
      - voyagrr-net

  sharing-service-database:
    image: postgres:17
    environment:
      POSTGRES_DB: sharing_service_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5436:5432'
    volumes:
      - sharing-database-data:/var/lib/postgresql/data
    networks:
      - voyagrr-net

  encoding-service-database:
    image: postgres:17
    environment:
      POSTGRES_DB: encoding_service_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5437:5432'
    volumes:
      - encoding-database-data:/var/lib/postgresql/data
    networks:
      - voyagrr-net

  eureka:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    ports:
      - '8761:8761'
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - voyagrr-net

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - voyagrr-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    depends_on:
      - keycloak-database
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_HTTP_PORT: 8070
    ports:
      - "8070:8070"
    networks:
      - voyagrr-net

  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio-data:/data
    networks:
      - voyagrr-net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - eureka
      - api-gateway
      - user-service-database
      - keycloak
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-database:5432/user_service_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - voyagrr-net

  storage-service:
    build:
      context: .
      dockerfile: storage-service/Dockerfile
    ports:
      - '8082:8082'
      - '9090:9090'
    depends_on:
      - eureka
      - api-gateway
      - storage-service-database
      - minio
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://storage-service-database:5432/storage_service_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - voyagrr-net

  sharing-service:
    build:
      context: .
      dockerfile: sharing-service/Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    expose:
      - '8083'
    depends_on:
      - eureka
      - api-gateway
      - sharing-service-database
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://sharing-service-database:5432/sharing_service_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - voyagrr-net

  encoding-service:
    build:
      context: .
      dockerfile: encoding-service/Dockerfile
    ports:
      - '8084:8084'
    depends_on:
      - eureka
      - api-gateway
      - encoding-service-database
      - minio
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://encoding-service-database:5432/encoding_service_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - voyagrr-net


volumes:
  keycloak-database-data:
  user-database-data:
  storage-database-data:
  sharing-database-data:
  encoding-database-data:
  minio-data:

networks:
  voyagrr-net:
    driver: bridge