server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: local

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**, /api/user/**
            - id: storage-service
              uri: lb://storage-service
              predicates:
                - Path=/api/storage/**, /api/directory/**
            - id: sharing-service
              uri: lb://sharing-service
              predicates:
                - Path=/api/share/**, /api/group/**
            - id: encoding-service
              uri: lb://encoding-service
              predicates:
                - Path=/api/encode/**

            - id: user-service-prometheus
              uri: http://user-service:8081
              predicates:
                - Path=/user-service/actuator/prometheus
              filters:
                - StripPrefix=1

            - id: storage-service-prometheus
              uri: http://storage-service:8082
              predicates:
                - Path=/storage-service/actuator/prometheus
              filters:
                - StripPrefix=1

            - id: sharing-service-prometheus
              uri: http://sharing-service:8083
              predicates:
                - Path=/sharing-service/actuator/prometheus
              filters:
                - StripPrefix=1

            - id: encoding-service-prometheus
              uri: http://encoding-service:8084
              predicates:
                - Path=/encoding-service/actuator/prometheus
              filters:
                - StripPrefix=1