server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**, /api/user/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 2
                    key-resolver: "#{@ipKeyResolver}"
            - id: storage-service
              uri: lb://storage-service
              predicates:
                - Path=/api/storage/**, /api/directory/**, /api/share/**, /api/group/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 2
                    redis-rate-limiter.burstCapacity: 5
                    key-resolver: "#{@userKeyResolver}"
            - id: processing-service
              uri: lb://processing-service
              predicates:
                - Path=/api/metadata/**
            - id: trip-service
              uri: lb://trip-service
              predicates:
                - Path=/api/trip/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 2
                    redis-rate-limiter.burstCapacity: 5
                    key-resolver: "#{@userKeyResolver}"

            - id: user-service-prometheus
              uri: lb://user-service
              predicates:
                - Path=/user-service/actuator/prometheus
              filters:
                - StripPrefix=1
            - id: storage-service-prometheus
              uri: lb://storage-service
              predicates:
                - Path=/storage-service/actuator/prometheus
              filters:
                - StripPrefix=1
            - id: processing-service-prometheus
              uri: lb://processing-service
              predicates:
                - Path=/processing-service/actuator/prometheus
              filters:
                - StripPrefix=1
            - id: trip-service-prometheus
              uri: lb://trip-service
              predicates:
                - Path=/trip-service/actuator/prometheus
              filters:
                - StripPrefix=1

logging:
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://tempo:4318/v1/traces
  metrics:
    tags:
      application: api-gateway
  prometheus:
    metrics:
      export:
        enabled: true
