server:
  port: 8085
  forward-headers-strategy: framework

spring:
  application:
    name: metadata-service

  liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog.master.yaml

logging:
  level:
    liquibase: INFO

management:
  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: metadata-service

  prometheus:
    metrics:
      export:
        enabled: true
