kafka:
  bootstrap_servers: localhost:9092
  topic_uploaded: file.uploaded.v1

postgres:
  url: postgresql://postgres:postgres@localhost:5439/metadata_service_database

minio:
  endpoint: localhost:9000
  access-key: minio
  secret-key: minio123
  secure: False
  bucket: voyagrr-media
