kafka:
  bootstrap_servers: kafka:9092
  topic_analyze: trip.analyze.v1
  topic_ai_result: file.analyzed.v1
  topic_embedding: image.embedding.v1

minio:
  endpoint: minio:9000
  access-key: minioadmin
  secret-key: minioadmin123
  secure: false
  bucket: voyagrr-media

postgres:
  url: postgresql://postgres:postgres@recognition-service-database:5432/recognition_service_database

app:
  temp_dir: /tmp/recognition
  match_threshold: 0.6
  max_workers: 4
