spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8070/realms/voyagrr

  datasource:
    url: jdbc:postgresql://user-service-database:5432/user_service_database
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

keycloak:
  keycloak-url: http://keycloak:8070
  realm: voyagrr
  client-id: voyagrr-client
  client-secret: ulB2DYKDZTAsy5eSKX1KCoPnrDVOw9BD

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus