server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: user-service

  profiles:
    active: local

management:
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: user-service

  prometheus:
    metrics:
      export:
        enabled: true