server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: user-service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.master.yaml

logging:
  level:
    liquibase: INFO

management:
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: user-service
  prometheus:
    metrics:
      export:
        enabled: true
