spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      properties:
        spring.json.add.type.headers: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring.json.use.type.headers: false
    properties:
      acks: all
      retries: 5
      enable.idempotence: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.master.yaml
  datasource:
    url: jdbc:postgresql://${STORAGE_DB_HOST}:${STORAGE_DB_PORT}/${STORAGE_DB_NAME}
    username: ${STORAGE_DB_USER}
    password: ${STORAGE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

minio:
  url: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
  processed-video-bucket: ${PROCESSED_VIDEO_BUCKET}

grpc:
  client:
    processing-service:
      address: static://processing-service:${PROCESSING_GRPC_SERVICE_PORT}
      negotiationType: plaintext
  server:
    port: ${STORAGE_GRPC_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
