server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: storage-service

management:
  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: storage-service

  prometheus:
    metrics:
      export:
        enabled: true