spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8070/realms/voyagrr/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://storage-service-database:5432/storage_service_database
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: voyagrr-media