spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}

  datasource:
    url: jdbc:postgresql://${STORAGE_DB_HOST}:${STORAGE_DB_PORT}/${STORAGE_DB_NAME}
    username: ${STORAGE_DB_USER}
    password: ${STORAGE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

grpc:
  client:
    sharing-service:
      address: static://sharing-service:${SHARING_GRPC_SERVICE_PORT}
      negotiationType: plaintext

  server:
    port: ${STORAGE_GRPC_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus