spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8070/realms/voyagrr

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5436/sharing_service_database
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

grpc:
  client:
    storage-service:
      address: static://localhost:9091
      negotiationType: plaintext

  server:
    port: 9090
