spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.master.yaml
  datasource:
    url: jdbc:postgresql://${SHARING_DB_HOST}:${SHARING_DB_PORT}/${SHARING_DB_NAME}
    username: ${SHARING_DB_USER}
    password: ${SHARING_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

grpc:
  client:
    storage-service:
      address: static://storage-service:${STORAGE_GRPC_SERVICE_PORT}
      negotiationType: plaintext
  server:
    port: ${SHARING_GRPC_SERVICE_PORT}
