server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: sharing-service

  profiles:
    active: local

grpc:
  server:
    port: 9090

management:
  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: sharing-service


  prometheus:
    metrics:
      export:
        enabled: true